apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLables:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: my-node-app
        image: anandubale11/pipelineone_1:latest
        imagePullPolicy: Always
        # ports:
        # - containerPort:8085

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: node-app
  # ports:
  #   -protocol: TCP
  #    port: 8080
  type:LoadBalancer
